// Modified namespace for tests

using UnityEngine;

namespace DUCK.Localisation.Tests
{
	public class Keys
	{
		public enum Test
		{
			Key1 = 778295567,
			Key2 = 778295568,
			Key3 = 778295569
		}
	}

	public class Loc
	{
		// Autogenerated code: please make changes to the template file and re-generate
		public static string Get(object key)
		{
			var target = string.Empty;
			try
			{
				var success = Get((int)key, out target);

				if (!success)
				{
					Debug.LogError(string.Format("Localisation value not found: {0}", key));
				}
			}
			catch (System.InvalidCastException e)
			{
				Debug.LogError(string.Format("Localisation key could not be cast to int: {0}", key));
			}

			return target;
		}

		// Autogenerated code: please make changes to the template file and re-generate
		public static bool Get(int key, out string target)
		{
			if (!DUCK.Localisation.Localiser.GetLocalisedString(key, out target))
			{
				target = string.Empty;
				return false;
			}

			return true;
		}
	}

	public class Config
	{
		public const string LOCALISATION_DATA_PATH = "Localisation";
	}
}